name: Deploy to Cloud Run

on:
  push:
    branches: [main]

jobs:
  db-migration:
    runs-on: ubuntu-latest

    steps:
      - name: Download Cloud SQL Auth Proxy
        run: |
          curl -o cloud_sql_proxy https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64
          chmod +x cloud_sql_proxy

      - name: Start Cloud SQL Auth Proxy
        run: |
          ./cloud_sql_proxy \
            -instances=${{ secrets.CLOUD_SQL_INSTANCE_CONNECTION_NAME }}=tcp:5432 &
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run DB Migrations
        env:
          DATABASE_URL: postgres://${{ secrets.DATABASE_USER }}:${{ secrets.DATABASE_PASSWORD }}@127.0.0.1:5432/${{ secrets.DATABASE_NAME }}
        run: |
          npx prisma migrate deploy