name: Deploy to Cloud Run

on:
  push:
    branches: [main] # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Configure gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: YOUR_PROJECT_ID

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker REGION-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          IMAGE="REGION-docker.pkg.dev/YOUR_PROJECT_ID/REPO_NAME/IMAGE_NAME"
          docker build -t "$IMAGE:$GITHUB_SHA" .
          docker push "$IMAGE:$GITHUB_SHA"

      - name: Deploy to Cloud Run
  run: |
    gcloud run deploy SERVICE_NAME \
      --image=REGION-docker.pkg.dev/YOUR_PROJECT_ID/REPO_NAME/IMAGE_NAME:$GITHUB_SHA \
      --platform=managed \
      --region=REGION \
      --allow-unauthenticated \
      --set-env-vars=\
        DATABASE_URL=${{ secrets.DATABASE_URL }},\
        NODE_ENV=development,\
        APPLICATION_SECRET=${{ secrets.APPLICATION_SECRET }},\
        APPLICATION_URL=http://0.0.0.0:3001,\
        PORT=8080

