name: Deploy to Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Configure gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: extreme-lodge-461611-f2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build, tag, and push Docker image
        run: |
          IMAGE_NAME="synced-api"
          REGION="us-central1"
          PROJECT_ID="extreme-lodge-461611-f2"
          REPOSITORY="syncec-repository"
          SERVICE_NAME="synced-api-automated"
          VPC_CONNECTOR="my-vpc-connector"

          # Build image for linux/amd64
          docker build --platform=linux/amd64 -t ${IMAGE_NAME} .

          # Tag image for Google Artifact Registry
          docker tag ${IMAGE_NAME} ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE_NAME}

          # Push image to registry
          docker push ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE_NAME}

      - name: Deploy to Cloud Run
        run: |
          IMAGE_NAME="synced-api"
          REGION="us-central1"
          PROJECT_ID="extreme-lodge-461611-f2"
          REPOSITORY="syncec-repository"
          SERVICE_NAME="synced-api-automated"
          VPC_CONNECTOR="my-vpc-connector"

          gcloud run deploy ${SERVICE_NAME} \
            --image=${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE_NAME} \
            --region=${REGION} \
            --vpc-connector=${VPC_CONNECTOR} \
            --vpc-egress=all \
            --allow-unauthenticated \
            --set-env-vars="DATABASE_URL=${{ secrets.DATABASE_URL }},APPLICATION_SECRET=${{ secrets.APPLICATION_SECRET }},NODE_ENV=development,APPLICATION_URL=http://0.0.0.0:3001,DOCS_PASSWORD="
  run-migrations:
    - name: Download Cloud SQL Auth Proxy
      run: |
        curl -o cloud_sql_proxy https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64
        chmod +x cloud_sql_proxy

    - name: Start Cloud SQL Auth Proxy
      run: |
        ./cloud_sql_proxy \
          -instances=${{ secrets.CLOUD_SQL_INSTANCE_CONNECTION_NAME }}=tcp:5432 &
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Run DB Migrations
      env:
        DATABASE_URL: postgres://${{ secrets.DATABASE_USER }}:${{ secrets.DATABASE_PASSWORD }}@127.0.0.1:5432/${{ secrets.DATABASE_NAME }}
      run: |
        npx prisma migrate deploy
